import { MongoClient } from "mongodb";
import dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const uri = process.env.MONGODB_URI;
if (!uri) throw new Error("Missing MONGODB_URI");

const medicines = [
  ["Amoxicillin", "amoxicillin", "Oral", "500 mg"],
  ["Amoxicillin-clavulanate", "amoxicillin clavulanate", "Oral", "625 mg"],
  ["Azithromycin", "azithromycin", "Oral", "500 mg"],
  ["Ciprofloxacin", "ciprofloxacin", "Oral", "500 mg"],
  ["Levofloxacin", "levofloxacin", "Oral", "500 mg"],
  ["Doxycycline", "doxycycline", "Oral", "100 mg"],
  ["Cephalexin", "cephalexin", "Oral", "500 mg"],
  ["Cefixime", "cefixime", "Oral", "200 mg"],
  ["Cefuroxime", "cefuroxime", "Oral", "500 mg"],
  ["Metronidazole", "metronidazole", "Oral", "400 mg"],
  ["Tinidazole", "tinidazole", "Oral", "500 mg"],
  ["Ofloxacin", "ofloxacin", "Oral", "200 mg"],
  ["Norfloxacin", "norfloxacin", "Oral", "400 mg"],
  ["Rifaximin", "rifaximin", "Oral", "550 mg"],
  ["Nitrofurantoin", "nitrofurantoin", "Oral", "100 mg"],
  ["Fosfomycin", "fosfomycin", "Oral", "3 g"],
  ["Fluconazole", "fluconazole", "Oral", "150 mg"],
  ["Itraconazole", "itraconazole", "Oral", "100 mg"],
  ["Terbinafine", "terbinafine", "Oral", "250 mg"],
  ["Loperamide", "loperamide", "Oral", "2 mg"],
  ["Dicyclomine", "dicyclomine", "Oral", "20 mg"],
  ["Ondansetron", "ondansetron", "Oral", "4 mg"],
  ["Pantoprazole", "pantoprazole", "Oral", "40 mg"],
  ["Omeprazole", "omeprazole", "Oral", "20 mg"],
  ["Esomeprazole", "esomeprazole", "Oral", "40 mg"],
  ["Rabeprazole", "rabeprazole", "Oral", "20 mg"],
  ["Ranitidine", "ranitidine", "Oral", "150 mg"],
  ["Famotidine", "famotidine", "Oral", "20 mg"],
  ["Domperidone", "domperidone", "Oral", "10 mg"],
  ["Metoclopramide", "metoclopramide", "Oral", "10 mg"],
  ["Sucralfate", "sucralfate", "Oral", "1 g"],
  ["Oral Rehydration Solution", "ors", "Oral", "1 sachet"],
  ["Paracetamol", "paracetamol", "Oral", "500 mg"],
  ["Ibuprofen", "ibuprofen", "Oral", "400 mg"],
  ["Aceclofenac", "aceclofenac", "Oral", "100 mg"],
  ["Diclofenac", "diclofenac", "Oral", "50 mg"],
  ["Naproxen", "naproxen", "Oral", "250 mg"],
  ["Aspirin", "aspirin", "Oral", "75 mg"],
  ["Meloxicam", "meloxicam", "Oral", "7.5 mg"],
  ["Ketorolac", "ketorolac", "Oral", "10 mg"],
  ["Tramadol", "tramadol", "Oral", "50 mg"],
  ["Amitriptyline", "amitriptyline", "Oral", "10 mg"],
  ["Pregabalin", "pregabalin", "Oral", "75 mg"],
  ["Gabapentin", "gabapentin", "Oral", "300 mg"],
  ["Sertraline", "sertraline", "Oral", "50 mg"],
  ["Escitalopram", "escitalopram", "Oral", "10 mg"],
  ["Fluoxetine", "fluoxetine", "Oral", "20 mg"],
  ["Duloxetine", "duloxetine", "Oral", "30 mg"],
  ["Mirtazapine", "mirtazapine", "Oral", "15 mg"],
  ["Alprazolam", "alprazolam", "Oral", "0.25 mg"],
  ["Clonazepam", "clonazepam", "Oral", "0.5 mg"],
  ["Diazepam", "diazepam", "Oral", "5 mg"],
  ["Lorazepam", "lorazepam", "Oral", "1 mg"],
  ["Levothyroxine", "levothyroxine", "Oral", "25 mcg"],
  ["Carbimazole", "carbimazole", "Oral", "5 mg"],
  ["Metformin", "metformin", "Oral", "500 mg"],
  ["Gliclazide", "gliclazide", "Oral", "80 mg"],
  ["Glimepiride", "glimepiride", "Oral", "1 mg"],
  ["Sitagliptin", "sitagliptin", "Oral", "100 mg"],
  ["Linagliptin", "linagliptin", "Oral", "5 mg"],
  ["Vildagliptin", "vildagliptin", "Oral", "50 mg"],
  ["Pioglitazone", "pioglitazone", "Oral", "15 mg"],
  ["Empagliflozin", "empagliflozin", "Oral", "10 mg"],
  ["Dapagliflozin", "dapagliflozin", "Oral", "10 mg"],
  ["Amlodipine", "amlodipine", "Oral", "5 mg"],
  ["Telmisartan", "telmisartan", "Oral", "40 mg"],
  ["Losartan", "losartan", "Oral", "50 mg"],
  ["Valsartan", "valsartan", "Oral", "80 mg"],
  ["Olmesartan", "olmesartan", "Oral", "20 mg"],
  ["Hydrochlorothiazide", "hydrochlorothiazide", "Oral", "12.5 mg"],
  ["Chlorthalidone", "chlorthalidone", "Oral", "12.5 mg"],
  ["Furosemide", "furosemide", "Oral", "40 mg"],
  ["Spironolactone", "spironolactone", "Oral", "25 mg"],
  ["Propranolol", "propranolol", "Oral", "20 mg"],
  ["Atenolol", "atenolol", "Oral", "50 mg"],
  ["Metoprolol", "metoprolol", "Oral", "25 mg"],
  ["Bisoprolol", "bisoprolol", "Oral", "5 mg"],
  ["Atorvastatin", "atorvastatin", "Oral", "10 mg"],
  ["Rosuvastatin", "rosuvastatin", "Oral", "10 mg"],
  ["Simvastatin", "simvastatin", "Oral", "20 mg"],
  ["Clopidogrel", "clopidogrel", "Oral", "75 mg"],
  ["Ticagrelor", "ticagrelor", "Oral", "90 mg"],
  ["Warfarin", "warfarin", "Oral", "2 mg"],
  ["Apixaban", "apixaban", "Oral", "5 mg"],
  ["Rivaroxaban", "rivaroxaban", "Oral", "10 mg"],
  ["Heparin", "heparin", "Injection", "5000 IU"],
  ["Enoxaparin", "enoxaparin", "Injection", "40 mg"],
  ["Insulin regular", "insulin regular", "Injection", "10 units"],
  ["Insulin glargine", "insulin glargine", "Injection", "10 units"],
  ["Insulin aspart", "insulin aspart", "Injection", "10 units"],
  ["Salbutamol", "salbutamol", "Inhalation", "100 mcg"],
  ["Budesonide", "budesonide", "Inhalation", "200 mcg"],
  ["Formoterol", "formoterol", "Inhalation", "6 mcg"],
  ["Montelukast", "montelukast", "Oral", "10 mg"],
  ["Cetirizine", "cetirizine", "Oral", "10 mg"],
  ["Levocetirizine", "levocetirizine", "Oral", "5 mg"],
  ["Fexofenadine", "fexofenadine", "Oral", "120 mg"],
  ["Loratadine", "loratadine", "Oral", "10 mg"],
  ["Prednisolone", "prednisolone", "Oral", "10 mg"],
  ["Methylprednisolone", "methylprednisolone", "Oral", "4 mg"],
  ["Hydrocortisone", "hydrocortisone", "Topical", "1%"],
  ["Mupirocin", "mupirocin", "Topical", "2%"],
  ["Clotrimazole", "clotrimazole", "Topical", "1%"],
  ["Miconazole", "miconazole", "Topical", "2%"],
  ["Hydroxyzine", "hydroxyzine", "Oral", "25 mg"],
  ["Domperidone oral suspension", "domperidone", "Oral", "5 mg/5 mL"],
  ["Iron sucrose", "iron sucrose", "Injection", "100 mg"],
  ["Ferrous sulfate", "ferrous sulfate", "Oral", "325 mg"],
  ["Folic acid", "folic acid", "Oral", "5 mg"],
  ["Vitamin D3", "cholecalciferol", "Oral", "60,000 IU"],
  ["Calcium carbonate", "calcium carbonate", "Oral", "500 mg"],
  ["Multivitamin", "multivitamin", "Oral", "1 tablet"],
  ["B-complex", "b-complex", "Oral", "1 tablet"],
  ["Risek", "omeprazole", "Oral", "20 mg"],
  ["Pan-D", "pantoprazole domperidone", "Oral", "40 mg"],
  ["Zerodol-P", "aceclofenac paracetamol", "Oral", "1 tablet"],
  ["Taxim-O", "cefixime", "Oral", "200 mg"],
  ["Augmentin", "amoxicillin clavulanate", "Oral", "625 mg"],
  ["Azee", "azithromycin", "Oral", "500 mg"],
  ["Cetzine", "cetirizine", "Oral", "10 mg"],
  ["Dolo 650", "paracetamol", "Oral", "650 mg"],
  ["Spasmo-Proxyvon", "dicyclomine paracetamol", "Oral", "1 tablet"],
  ["Prega-Gaba", "pregabalin gabapentin", "Oral", "1 capsule"],
];

const client = new MongoClient(uri);
await client.connect();
const db = client.db("cliniq");

await db.collection("medication_catalog").bulkWrite(
  medicines.map(([name, generic_name, default_route, default_strength]) => ({
    updateOne: {
      filter: { name },
      update: {
        $set: {
          name,
          generic_name,
          default_route,
          default_strength,
          aliases: [generic_name, name.toLowerCase()],
          updated_at: new Date().toISOString(),
        },
        $setOnInsert: {
          created_at: new Date().toISOString(),
        },
      },
      upsert: true,
    },
  }))
);

console.log(`Seeded ${medicines.length} medication catalog entries.`);
await client.close();